### PR TITLE
Export nova metadata. Fixes #2

### LINKED ISSUE #2: Ability to configure additional labels
Nice project!

For us I'm looking for the ability to add more labels based on the `<metadata>` or `<sysinfo>` parts of the dom xml.

This is in my case to extract additional (openstack) information like instance uuid, flavor, name, creation date, project + user uuid etc.

Maybe I will implement this if the patch is welcome.

### PR DESCRIPTION
**Pull request by stefreak**

### CODE REVIEW

**Comment by stefreak** [comment]
@EdSchouten Hi! :) Here is the first version of a patch that will

1. Export the UUID of a domain as well as it's name (if it does not exist, it will be an empty string)
2. If the `--libvirt.export-nova-metadata` flag is given the exporter will provide additional OpenStack nova-specific labels like `name`, `flavor`, and `project_name`

I could not properly test it yet, as I am struggling with `./build_static.sh` – it seems to use the libvirt_schema from github instead of the local one. Building using the `Dockerfile` works.

What do you think about it?

**Comment by EdSchouten** [comment]
@BartVerc ^^

**Comment by stefreak** [comment]
@BartVerc @EdSchouten I now tested it, successfully extracted the binary from the Dockerfile :)

**Comment by stefreak** [comment]
@BartVerc @timstoop any thoughts on the merge request? :) I'd be really happy if you have a look.

Sorry that I had to touch so many lines; the problem is that all the `prometheus.Desc` objects needed to be initialized differently, depending on the command-line flag. That's why I changed them to be attributes of `LibvirtExporter`.

**Comment by BartVerc** [comment]
Hi @stefreak ,
Thanks for the PR! I've tested it and have a fix for the `build_static.sh` problem. 
I will merge this PR and add the fix.

**Comment by stefreak** [comment]
@BartVerc thank you for your time :)

**Pull request merged**
